// <auto-generated />
using System;
using FuseBox.App.DataBase;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FuseBox.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250316232440_AddProjectFuseBoxStructure")]
    partial class AddProjectFuseBoxStructure
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("FuseBox.App.Controllers.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("FuseBox.App.Models.BaseAbstract.BaseElectrical", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<double>("Amper")
                        .HasColumnType("double");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("varchar(21)");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("BaseElectrical");

                    b.HasDiscriminator<string>("Discriminator").HasValue("BaseElectrical");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("FuseBox.App.Models.Position", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ConnectionId")
                        .HasColumnType("int");

                    b.Property<int>("IndexFinish")
                        .HasColumnType("int");

                    b.Property<int>("IndexStart")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("ConnectionId")
                        .IsUnique();

                    b.ToTable("Positions");
                });

            modelBuilder.Entity("FuseBox.App.Models.Shild_Comp.Cable", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ConnectionId")
                        .HasColumnType("int");

                    b.Property<decimal>("Length")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<decimal>("Section")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("Сolour")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("ConnectionId")
                        .IsUnique();

                    b.ToTable("Cables");
                });

            modelBuilder.Entity("FuseBox.Connection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("FuseBoxUnitId")
                        .HasColumnType("int");

                    b.Property<int>("FuseBoxUnitId6")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("FuseBoxUnitId");

                    b.HasIndex("FuseBoxUnitId6");

                    b.ToTable("Connections");
                });

            modelBuilder.Entity("FuseBox.Floor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<int>("ProjectId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.ToTable("Floors");
                });

            modelBuilder.Entity("FuseBox.FloorGrouping", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IndividualFloorGrouping")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<int>("ProjectId")
                        .HasColumnType("int");

                    b.Property<bool>("SeparateUZOPerFloor")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId")
                        .IsUnique();

                    b.ToTable("FloorGroupings");
                });

            modelBuilder.Entity("FuseBox.FuseBox.InitialSettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("MainAmperage")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<int>("PhasesCount")
                        .HasColumnType("int");

                    b.Property<int>("PowerCoefficient")
                        .HasColumnType("int");

                    b.Property<int>("ProjectId")
                        .HasColumnType("int");

                    b.Property<int>("ShieldWidth")
                        .HasColumnType("int");

                    b.Property<int>("VoltageStandard")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId")
                        .IsUnique();

                    b.ToTable("InitialSettings");
                });

            modelBuilder.Entity("FuseBox.FuseBoxComponentGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("FuseBoxId")
                        .HasColumnType("int");

                    b.Property<int>("FuseBoxUnit5")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("FuseBoxId");

                    b.HasIndex("FuseBoxUnit5");

                    b.ToTable("FuseBoxComponentGroup");
                });

            modelBuilder.Entity("FuseBox.FuseBoxUnit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("CrossModule")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("DINLines")
                        .HasColumnType("int");

                    b.Property<bool>("FireUZO")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("LoadSwitch")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("LoadSwitch2P")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("Main3PN")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("MainBreaker")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("ModularContactor")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("NDiscLine")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int>("ProjectId")
                        .HasColumnType("int");

                    b.Property<bool>("RailMeter")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("RailSocket")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("SurgeProtection")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("ThreePRelay")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("VoltageRelay")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId")
                        .IsUnique();

                    b.ToTable("FuseBoxes");
                });

            modelBuilder.Entity("FuseBox.GlobalGrouping", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Conditioners")
                        .HasColumnType("int");

                    b.Property<int>("Lighting")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<int>("ProjectId")
                        .HasColumnType("int");

                    b.Property<int>("Sockets")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId")
                        .IsUnique();

                    b.ToTable("GlobalGroupings");
                });

            modelBuilder.Entity("FuseBox.Port", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<string>("PortIn")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("connectionsCount")
                        .HasColumnType("int");

                    b.Property<string>("portOut")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Ports");
                });

            modelBuilder.Entity("FuseBox.Project", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<double>("TotalPower")
                        .HasColumnType("double");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("FuseBox.Room", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("FloorId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("FloorId");

                    b.ToTable("Rooms");
                });

            modelBuilder.Entity("FuseBox.Component", b =>
                {
                    b.HasBaseType("FuseBox.App.Models.BaseAbstract.BaseElectrical");

                    b.Property<int?>("ContactorId")
                        .HasColumnType("int");

                    b.Property<int>("FuseBoxUnitId3")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int?>("RCDId")
                        .HasColumnType("int");

                    b.Property<int>("Slots")
                        .HasColumnType("int");

                    b.HasIndex("ContactorId");

                    b.HasIndex("FuseBoxUnitId3");

                    b.HasIndex("RCDId");

                    b.HasDiscriminator().HasValue("Component");
                });

            modelBuilder.Entity("FuseBox.Consumer", b =>
                {
                    b.HasBaseType("FuseBox.Component");

                    b.Property<int>("FuseBoxUnitId4")
                        .HasColumnType("int");

                    b.Property<int?>("FuseId")
                        .HasColumnType("int");

                    b.Property<int>("RoomId")
                        .HasColumnType("int");

                    b.HasIndex("FuseId");

                    b.HasIndex("RoomId");

                    b.HasDiscriminator().HasValue("Consumer");
                });

            modelBuilder.Entity("FuseBox.Contactor", b =>
                {
                    b.HasBaseType("FuseBox.Component");

                    b.HasDiscriminator().HasValue("Contactor");
                });

            modelBuilder.Entity("FuseBox.EmptySlot", b =>
                {
                    b.HasBaseType("FuseBox.Component");

                    b.HasDiscriminator().HasValue("EmptySlot");
                });

            modelBuilder.Entity("FuseBox.Fuse", b =>
                {
                    b.HasBaseType("FuseBox.Component");

                    b.HasDiscriminator().HasValue("Fuse");
                });

            modelBuilder.Entity("FuseBox.Introductory", b =>
                {
                    b.HasBaseType("FuseBox.Component");

                    b.Property<string>("Type")
                        .HasColumnType("longtext");

                    b.HasDiscriminator().HasValue("Introductory");
                });

            modelBuilder.Entity("FuseBox.RCD", b =>
                {
                    b.HasBaseType("FuseBox.Component");

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<double>("TotalLoad")
                        .HasColumnType("double");

                    b.HasDiscriminator().HasValue("RCD");
                });

            modelBuilder.Entity("FuseBox.RCDFire", b =>
                {
                    b.HasBaseType("FuseBox.Component");

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.ToTable("BaseElectrical", t =>
                        {
                            t.Property("Capacity")
                                .HasColumnName("RCDFire_Capacity");
                        });

                    b.HasDiscriminator().HasValue("RCDFire");
                });

            modelBuilder.Entity("FuseBox.App.Models.BaseAbstract.BaseElectrical", b =>
                {
                    b.HasOne("FuseBox.FuseBoxComponentGroup", null)
                        .WithMany("Components")
                        .HasForeignKey("Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FuseBox.App.Models.Position", b =>
                {
                    b.HasOne("FuseBox.Connection", "Connection")
                        .WithOne("CabelWay")
                        .HasForeignKey("FuseBox.App.Models.Position", "ConnectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Connection");
                });

            modelBuilder.Entity("FuseBox.App.Models.Shild_Comp.Cable", b =>
                {
                    b.HasOne("FuseBox.Connection", "Connection")
                        .WithOne("Cable")
                        .HasForeignKey("FuseBox.App.Models.Shild_Comp.Cable", "ConnectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Connection");
                });

            modelBuilder.Entity("FuseBox.Connection", b =>
                {
                    b.HasOne("FuseBox.FuseBoxUnit", "FuseBoxUnit")
                        .WithMany()
                        .HasForeignKey("FuseBoxUnitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FuseBox.FuseBoxUnit", null)
                        .WithMany("CableConnections")
                        .HasForeignKey("FuseBoxUnitId6")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FuseBoxUnit");
                });

            modelBuilder.Entity("FuseBox.Floor", b =>
                {
                    b.HasOne("FuseBox.Project", null)
                        .WithMany("Floors")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FuseBox.FloorGrouping", b =>
                {
                    b.HasOne("FuseBox.Project", "Project")
                        .WithOne("FloorGrouping")
                        .HasForeignKey("FuseBox.FloorGrouping", "ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("FuseBox.FuseBox.InitialSettings", b =>
                {
                    b.HasOne("FuseBox.Project", "Project")
                        .WithOne("InitialSettings")
                        .HasForeignKey("FuseBox.FuseBox.InitialSettings", "ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("FuseBox.FuseBoxComponentGroup", b =>
                {
                    b.HasOne("FuseBox.FuseBoxUnit", "FuseBox")
                        .WithMany()
                        .HasForeignKey("FuseBoxId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FuseBox.FuseBoxUnit", null)
                        .WithMany("Components")
                        .HasForeignKey("FuseBoxUnit5")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FuseBox");
                });

            modelBuilder.Entity("FuseBox.FuseBoxUnit", b =>
                {
                    b.HasOne("FuseBox.Project", "Project")
                        .WithOne("FuseBox")
                        .HasForeignKey("FuseBox.FuseBoxUnit", "ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("FuseBox.GlobalGrouping", b =>
                {
                    b.HasOne("FuseBox.Project", "Project")
                        .WithOne("GlobalGrouping")
                        .HasForeignKey("FuseBox.GlobalGrouping", "ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("FuseBox.Project", b =>
                {
                    b.HasOne("FuseBox.App.Controllers.User", null)
                        .WithMany("Projects")
                        .HasForeignKey("UserId");
                });

            modelBuilder.Entity("FuseBox.Room", b =>
                {
                    b.HasOne("FuseBox.Floor", null)
                        .WithMany("Rooms")
                        .HasForeignKey("FloorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FuseBox.Component", b =>
                {
                    b.HasOne("FuseBox.Contactor", null)
                        .WithMany("Electricals")
                        .HasForeignKey("ContactorId");

                    b.HasOne("FuseBox.FuseBoxUnit", "FuseBoxUnit")
                        .WithMany("Electricals")
                        .HasForeignKey("FuseBoxUnitId3")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FuseBox.RCD", null)
                        .WithMany("Electricals")
                        .HasForeignKey("RCDId");

                    b.Navigation("FuseBoxUnit");
                });

            modelBuilder.Entity("FuseBox.Consumer", b =>
                {
                    b.HasOne("FuseBox.Fuse", null)
                        .WithMany("Electricals")
                        .HasForeignKey("FuseId");

                    b.HasOne("FuseBox.Room", null)
                        .WithMany("Consumer")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FuseBox.App.Controllers.User", b =>
                {
                    b.Navigation("Projects");
                });

            modelBuilder.Entity("FuseBox.Connection", b =>
                {
                    b.Navigation("CabelWay")
                        .IsRequired();

                    b.Navigation("Cable")
                        .IsRequired();
                });

            modelBuilder.Entity("FuseBox.Floor", b =>
                {
                    b.Navigation("Rooms");
                });

            modelBuilder.Entity("FuseBox.FuseBoxComponentGroup", b =>
                {
                    b.Navigation("Components");
                });

            modelBuilder.Entity("FuseBox.FuseBoxUnit", b =>
                {
                    b.Navigation("CableConnections");

                    b.Navigation("Components");

                    b.Navigation("Electricals");
                });

            modelBuilder.Entity("FuseBox.Project", b =>
                {
                    b.Navigation("FloorGrouping")
                        .IsRequired();

                    b.Navigation("Floors");

                    b.Navigation("FuseBox")
                        .IsRequired();

                    b.Navigation("GlobalGrouping")
                        .IsRequired();

                    b.Navigation("InitialSettings")
                        .IsRequired();
                });

            modelBuilder.Entity("FuseBox.Room", b =>
                {
                    b.Navigation("Consumer");
                });

            modelBuilder.Entity("FuseBox.Contactor", b =>
                {
                    b.Navigation("Electricals");
                });

            modelBuilder.Entity("FuseBox.Fuse", b =>
                {
                    b.Navigation("Electricals");
                });

            modelBuilder.Entity("FuseBox.RCD", b =>
                {
                    b.Navigation("Electricals");
                });
#pragma warning restore 612, 618
        }
    }
}
